name: Build ZMK firmware
on:
  workflow_dispatch: # can be triggered manually
  push:
    paths:
      - ".github/workflows/build.yml"
      - "config/*.keymap"
      - "config/*.conf"
      - "config/west.yml"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
